sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 5.0
services: docker
before_install:
   - cd RestWithASPNET5_SQLAPI/
   -echo "We are in the right folder!"
script:
 -docker-compose build

before_deploy:
  -echo "$DOCKER_PASSWORD" | docker login --username "tanisantos" --password-stdin
 deploy:
   provider: script
   script:
    docker tag rest-with-asp-net-udemy:$latest tanisantos/rest-with-asp-net-udemy:$TRAVIS_JOB_ID;
    tag rest-with-asp-net-udemy-db:$latest tanisantos/rest-with-asp-net-udemy-db:$TRAVIS_JOB_ID;
    docker push tanisantos/rest-with-asp-net-udemy:$TRAVIS_JOB_ID;
    docker push tanisantos/rest-with-asp-net-udemy-db:$TRAVIS_JOB_ID;
   on:
    branch: master
notifications:
  email: false